name: Create pull request

on:
  workflow_call:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest 
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v3

      - name: Version Increment
        id: version
        run: |
          echo "**********************"
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          npm version minor -m "v%s"
          version=$(node -p "require('./package.json').version")
          echo "::set-output name=version::${version}"
          echo "**********************"
        
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Create pull request
          committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: ${{ github.ref }}
          delete-branch: true
          base: production
          title: 'v${{ steps.version.outputs.version }} release'
          body: |
            # Cambios
            <!-- Incluya un resumen del cambio y qué problema se solucionó. -->
            <!-- Incluya también la motivación y el contexto pertinentes. -->
            <!-- Enumere las dependencias necesarias para este cambio. -->

            Fixes # (issue)


            ## De qué se trata este PR

            - Ingrese una breve descripción para este PR


            ### Ejecuciones de prueba

            - [Run actions](<>)


            ## Tipo de cambio
            <!-- Elimine las opciones que no sean relevantes. -->
            - [ ] 📚 Actualización de documentación
            - [ ] 🧪 Casos de prueba
            - [ ] 🐞 Corrección de errores (cambio continuo que soluciona un problema)
            - [ ] 🔬 Nueva característica (cambio continuo que agrega funcionalidad)
            - [ ] 🚨 Cambio importante (corrección o característica que haría que la funcionalidad existente no funcionara como se esperaba)
            - [ ] 📝 Este cambio requiere una actualización de documentación


            ## Checklist

            - [ ] Mi código sigue las pautas de estilo de este proyecto
            - [ ] He realizado una auto-revisión de mi propio código
            - [ ] He comentado mi código, particularmente en áreas difíciles de entender
            - [ ] He realizado los cambios correspondientes a la documentación.
            - [ ] Mis cambios no generan nuevas advertencias
            - [ ] ¿Actualizó CHANGELOG en caso de un cambio importante?
          labels: |
            automated pr
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
          draft: false
